[defaults]
file = ""
directory =""

[file_exact]
makefile = ""

[ext]
c = ""
cpp = ""
cs = ""
css = ""
html = ""
jar = ""
js = ""
json = ""
yaml = ""
ini = "󰅪"
lua = ""
pdf = ""
py = ""
rb = ""
rs = ""
sh = ""
toml = ""
png = ""
jpg = ""
jpeg = ""
svg = "󰜡"
md = ""
bak = "󰁯"
xml = "󰗀"
bin = ""
xcf = ""
ttf = ""
zip = ""
rar = ""
7z = ""
tar = ""
