# vim:ft=kitty

## name:     Gruvbox Material
## author:   sainhhe, ported by xemanue

# The basic colors
foreground              #ddc7a1
background              #32302f
selection_foreground    #ddc7a1
selection_background    #45403d

# Cursor colors
cursor                  #e78a4e
cursor_text_color       #32302f

# URL underline color when hovering with mouse
url_color               #7daea3

# Tab bar colors
active_tab_foreground   #32302f
active_tab_background   #e78a4e
inactive_tab_foreground #ddc7a1
inactive_tab_background #32302f
tab_bar_background      #32302f

# The 16 terminal colors

# black
color0 #928374
color8 #7c6f64

# red
color1 #ea6962
color9 #d35e58

# green
color2  #a9b665
color10 #98a45b

# yellow
color3  #d8a657
color11 #c2954e

# blue
color4  #7daea3
color12 #709f93

# magenta
color5  #d3869b
color13 #be798c

# cyan
color6  #89b482
color14 #7ba275

# white
color7  #ddc7a1
color15 #c7b391
