background {
    monitor =
    color = rgb(11111b)

    blur_passes = 0
}

input-field {
    monitor =
    
    size = 200, 50
    outline_thickness = 2

    dots_size = 0.25
    dots_spacing = 0.1
    dots_rounding = -1
    dots_fade_time = 100
}
