$theme = mellow

source = $HOME/.config/hypr/hyprland/general.conf
source = $HOME/.config/hypr/hyprland/keybinds.conf
source = $HOME/.config/hypr/hyprland/execs.conf
source = $HOME/.config/hypr/hyprland/rules.conf
source = $HOME/.config/hypr/hyprland/envs.conf
source = $HOME/.config/hypr/hyprland/themes/$theme.conf
