;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

include-file = $HOME/.config/polybar/color_palettes/mocha.ini

[colors]
background = ${mocha.base}
background-alt = ${mocha.surface0}
border = ${mocha.mantle}
foreground = ${mocha.text}
primary = ${mocha.mauve}
secondary = ${mocha.yellow}
alert = ${mocha.yellow}
disabled = ${mocha.overlay0}

[bar/mine]
width = 100%
height = 24pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

; Workspace indicator
line-size = 2pt

border-size = 2pt
border-color = ${colors.border}

padding-left = 0
padding-right = 1

module-margin = 1
separator = |
separator-foreground = ${colors.disabled}

font-0 = "JetBrainsMono NFM SemiBold; 3"

modules-left = xworkspaces
modules-right = pulseaudio battery-combined-udev memory cpu filesystem wlan xkeyboard date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true


[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1


[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#cba6f7}MEM%{F-} %used% / %total%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}


[module/battery-combined-udev]
type = custom/script
exec = ~/.config/polybar/custom_scripts/battery-combined-udev.sh
tail = true

format-prefix = "BAT "
format-prefix-foreground = ${colors.primary}


[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = %{F#6c7086}VOL %{F#cdd6f4}%percentage%%


[module/xkeyboard]
type = internal/xkeyboard

label-layout = %icon%
label-layout-foreground = ${colors.primary}
layout-icon-0 = es;ES
layout-icon-1 = us;US

label-indicator-on-capslock = "%{F#cba6f7}CL "
label-indicator-off-capslock = "%{F#6c7086}CL "
label-indicator-on-numlock = "%{F#6c7086}NL"
label-indicator-off-numlock = "%{F#cba6f7}NL"


[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%


[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%


[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected


[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#cba7f7}%ifname%%{F-} %essid% %local_ip%
label-disconnected = %{F#cba6f7}%ifname%%{F-} %{F#6c7086}disconnected


[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#f38ba8}%ifname%%{F-} %local_ip%


[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %d-%m-%y %H:%M:%S

label = %date%
label-foreground = ${colors.primary}


[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
