bind = super, return, exec, foot
bind = super shift, Q, killactive, 
bind = super, escape, exit, 
bind = super, e, exec, thunar
bind = super, space, togglefloating, 
bind = super, d, exec, rofi -modi drun -show drun -config "$HOME/.config/rofi/$theme/config.rasi"
bind = super, w, togglesplit,
bind = super, f, fullscreen, 1
bind = super, c, centerwindow

# Move focus
bind = super, h, movefocus, l
bind = super, l, movefocus, r
bind = super, k, movefocus, u
bind = super, j, movefocus, d
bind = super, left, movefocus, l
bind = super, right, movefocus, r
bind = super, up, movefocus, u
bind = super, down, movefocus, d

# Move windows
bind = super shift, h, movewindow, l
bind = super shift, l, movewindow, r
bind = super shift, k, movewindow, u
bind = super shift, j, movewindow, d
bind = super shift, left, movewindow, l
bind = super shift, right, movewindow, r
bind = super shift, up, movewindow, u
bind = super shift, down, movewindow, d

# Switch workspaces
bind = super, mouse_down, workspace, e+1
bind = super, mouse_up, workspace, e-1

bind = super, 1, workspace, 1
bind = super, 2, workspace, 2
bind = super, 3, workspace, 3
bind = super, 4, workspace, 4
bind = super, 5, workspace, 5
bind = super, 6, workspace, 6
bind = super, 7, workspace, 7
bind = super, 8, workspace, 8
bind = super, 9, workspace, 9
bind = super, 0, workspace, 10

# Move active window to workspace
bind = super, mouse_down, movetoworkspace, e+1
bind = super, mouse_up, movetoworkspace, e-1

bind = super shift, 1, movetoworkspace, 1
bind = super shift, 2, movetoworkspace, 2
bind = super shift, 3, movetoworkspace, 3
bind = super shift, 4, movetoworkspace, 4
bind = super shift, 5, movetoworkspace, 5
bind = super shift, 6, movetoworkspace, 6
bind = super shift, 7, movetoworkspace, 7
bind = super shift, 8, movetoworkspace, 8
bind = super shift, 9, movetoworkspace, 9
bind = super shift, 0, movetoworkspace, 10

# Scratchpad
bind = super, s, togglespecialworkspace, s
bind = super shift, s, movetoworkspace, special:s

# Move/resize windows
bindm = super, mouse:272, movewindow
bindm = super, mouse:273, resizewindow
