# windowrulev2 = suppressevent maximize, class:.*

# Windows opened on special workspace will float
windowrulev2 = float, onworkspace:s[true]
windowrulev2 = center,  onworkspace:s[true]
windowrulev2 = size 1000 635, onworkspace:s[true]
